### ISSUE TITLE
Formulierung der Unwucht in Kapitel 2.1

### ISSUE THREAD

**Issue by StefanFW** [schnes4/dhbw-heidenheim-semester-paper-doc#18]
Zur Auswahl stehen:

- Eine Unwucht ist eine Rotation, welche bei einem rotierenden Körper nicht in der Hauptträgheitsachse stattfindet, sondern leicht versetzt.
-Eine Unwucht ist eine Rotation eines rotierenden Körpers, welche leicht versetzt zur Hauptträgheitsachse stattfindet.

**Comment by ghost** [comment]
Bin für letzteres.

**Comment by StefanFW** [comment]
wie jetzt doch oder was??? Des erste ist das was von dir kommt und du wolltest doch dran festhalten...

**Comment by ghost** [comment]
Tja .. so ändert sich die Meinung nach ein paar Stunden :wink:
