### ISSUE TITLE
Update der Semesterarbeit auf aktuelle Templateversion

### ISSUE THREAD

**Issue by ghost** [schnes4/dhbw-heidenheim-semester-paper-doc#19]
Wir sollten uns überlegen ob wir die Semesterarbeit auf die aktuellste Templateversion updaten. Damit bekommen wir einerseits das Feature mit dem Abstand für Figures, als auch eventuell den PR für das neue Aussehen der Code-Listings.

**Comment by StefanFW** [comment]
bist du mit dem update script schon so weit, dass wir gleich das verwenden können (also mit einem crunsh so dass nur ein commit mit nem update tag rein kommt)?

**Comment by ghost** [comment]
Das update script verwendet aktuell einen merge --squash. Bedeutet dass im endeffekt das gesamte update des templates in nur einem einzigen commit steckt.

Man sieht jetzt eben nicht dass eine änderung von "außen" kam, sondern es sieht so aus als ob die änderungen einfach "manuell" in *diesem* commit passiert wären.

**Comment by ghost** [comment]
Mit PR #32 geschlossen
