### ISSUE TITLE
Wochenzahl

### ISSUE THREAD

**Issue by StefanFW** [schnes4/dhbw-heidenheim-semester-paper-doc#7]
Was müssen wir eigentlich bei der Anzahl der Wochen reinschreiben?
Wie lange ging die Studienarbeit jetzt?

**Comment by ghost** [comment]
Da es keine offiziellen Angaben über den Anfang __und__ das Ende der Studienarbeit gibt, würde ich vorschlagen wir schreiben unseren tatsächlichen Beginn rein. Die Studienarbeit beläuft sich dann auf 15 Wochen und 5 Tage. Runden wir auf oder ab?

**Comment by StefanFW** [comment]
Ok können wir machen (ich würde sagen auf denn 5 Tage sind ja eig schon a Woche...)
